### ISSUE TITLE
Hello creeperplayer how come you deleted discord?

### ISSUE THREAD

**Issue by MFDGaming** [creeperplayer20/ProfileUI#2]

**Comment by MFDGaming** [comment]
@creeperplayer20

**Comment by erstar2005** [comment]
hello

**Comment by MFDGaming** [comment]
hello

**Comment by erstar2005** [comment]
hello

**Comment by creeperplayer20** [comment]
Hi 👋, i got banned... 👉👈

My discord name: creeperplayer20#0031

**Comment by erstar2005** [comment]
wtf why were you banned? lol!

**Comment by creeperplayer20** [comment]
I was in the bad discord server, then i got banned  from discord 😞

**Comment by erstar2005** [comment]
may i ask what kind of discord server was that (for not getting in there)?
